In [3]:
import pandas as pd
import numpy as np

In [20]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [21]:
mydata = pd.read_csv('/content/drive/MyDrive/Deep Learning/train.csv/train.csv')

In [22]:
mydata.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [23]:
mydata = mydata.dropna()

In [24]:
X = mydata.drop('label',axis=1)

In [25]:
y=mydata['label']

In [26]:
X.shape

(18285, 4)

In [27]:
y.shape

(18285,)

In [28]:
import tensorflow as tf

In [29]:
tf.__version__

'2.6.0'

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [31]:
voc_size=5000

In [32]:
messages=X.copy()

In [33]:
messages.reset_index(inplace=True)

In [34]:
import nltk
import re
from nltk.corpus import stopwords

In [35]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [36]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [37]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [38]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1956, 4678, 3181, 576, 19, 3635, 2592, 778, 3454, 1912],
 [2365, 3650, 3195, 3834, 4938, 4867, 1665],
 [421, 4487, 1589, 3381],
 [3626, 101, 1151, 3678, 1509, 3796],
 [2697, 4938, 3425, 934, 1926, 2358, 4938, 309, 28, 595],
 [1388,
  1805,
  2765,
  4823,
  1483,
  1244,
  3475,
  2875,
  4249,
  1253,
  4317,
  1055,
  474,
  746,
  1665],
 [3713, 740, 4985, 302, 2505, 2576, 1893, 4230, 2313, 987, 2893],
 [683, 760, 4735, 3758, 1464, 327, 1244, 285, 2313, 987, 2893],
 [4766, 3300, 1799, 4410, 1834, 1838, 3252, 2048, 1244, 1005],
 [1281, 1706, 4605, 2533, 43, 2150, 1836, 1409],
 [2838, 4584, 91, 1664, 1949, 2595, 738, 3587, 2221, 2002, 875],
 [3678, 646, 19, 1838, 1244, 1464],
 [59, 3681, 1208, 800, 2034, 4549, 4136, 4478, 2967],
 [1145, 2972, 719, 4987, 1725, 1106, 4164, 2313, 987, 2893],
 [1887, 718, 4774, 2404, 1713, 2313, 987, 2893],
 [4332, 89, 3954, 970, 260, 407, 392, 4586, 3649, 3932],
 [1712, 2581, 3650],
 [948, 1306, 2549, 468, 1244, 4085, 2931, 1665],
 [2156, 66, 3195, 427

In [39]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  778 3454 1912]
 [   0    0    0 ... 4938 4867 1665]
 [   0    0    0 ... 4487 1589 3381]
 ...
 [   0    0    0 ... 2313  987 2893]
 [   0    0    0 ... 3907 3220  831]
 [   0    0    0 ... 4251 2067 4766]]


In [40]:

embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1956,
       4678, 3181,  576,   19, 3635, 2592,  778, 3454, 1912], dtype=int32)

In [41]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [42]:

len(embedded_docs),y.shape

(18285, (18285,))

In [43]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [45]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 8s 32ms/step - loss: 0.3291 - accuracy: 0.8442 - val_loss: 0.1972 - val_accuracy: 0.9181
Epoch 2/10
192/192 [==============================] - 6s 30ms/step - loss: 0.1379 - accuracy: 0.9458 - val_loss: 0.2057 - val_accuracy: 0.9102
Epoch 3/10
192/192 [==============================] - 6s 29ms/step - loss: 0.1022 - accuracy: 0.9628 - val_loss: 0.2148 - val_accuracy: 0.9193
Epoch 4/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0699 - accuracy: 0.9767 - val_loss: 0.2449 - val_accuracy: 0.9118
Epoch 5/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0507 - accuracy: 0.9822 - val_loss: 0.2959 - val_accuracy: 0.9162
Epoch 6/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0331 - accuracy: 0.9900 - val_loss: 0.3521 - val_accuracy: 0.9090
Epoch 7/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0201 - accuracy: 0.9930 - val_loss: 0.4126 - val_accuracy: 0.9150

In [46]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [55]:
predict_x=model.predict(X_test) 
classes_x=np.argmax(predict_x,axis=1)

In [56]:
from sklearn.metrics import confusion_matrix

In [58]:

confusion_matrix(y_test,classes_x)

array([[3419,    0],
       [2616,    0]])

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,classes_x)

0.5665285832642917